// src/flags.js
const flags = {
    USD: 'https://example.com/flags/usd.png',
    EUR: 'https://example.com/flags/eur.png',
    GBP: 'https://example.com/flags/gbp.png',
    JPY: 'https://example.com/flags/jpy.png',
    AUD: 'https://example.com/flags/aud.png',
    CAD: 'https://example.com/flags/cad.png',
    CHF: 'https://example.com/flags/chf.png',
    CNY: 'https://example.com/flags/cny.png',
    SEK: 'https://example.com/flags/sek.png',
    NZD: 'https://example.com/flags/nzd.png',
    ZAR: 'https://example.com/flags/zar.png',
    NGN: 'https://example.com/flags/ngn.png',
    EGP: 'https://example.com/flags/egp.png',
    KES: 'https://example.com/flags/kes.png',
    GHS: 'https://example.com/flags/ghs.png',
    TZS: 'https://example.com/flags/tzs.png',
    UGX: 'https://example.com/flags/ugx.png',
    MAD: 'https://example.com/flags/mad.png',
    DZD: 'https://example.com/flags/dzd.png',
    AOA: 'https://example.com/flags/aoa.png',
    XOF: 'https://example.com/flags/xof.png',
    XAF: 'https://example.com/flags/xaf.png',
    BWP: 'https://example.com/flags/bwp.png',
    MUR: 'https://example.com/flags/mur.png',
    NAD: 'https://example.com/flags/nad.png',
    ZMW: 'https://example.com/flags/zmw.png',
    ETB: 'https://example.com/flags/etb.png',
    CDF: 'https://example.com/flags/cdf.png',
    LRD: 'https://example.com/flags/lrd.png',
    SLL: 'https://example.com/flags/sll.png',
    SZL: 'https://example.com/flags/szl.png',
    MWK: 'https://example.com/flags/mwk.png',
    MZN: 'https://example.com/flags/mzn.png',
    SCR: 'https://example.com/flags/scr.png',
    SOS: 'https://example.com/flags/sos.png',
    LSL: 'https://example.com/flags/lsl.png',
    DJF: 'https://example.com/flags/djf.png',
    ERN: 'https://example.com/flags/ern.png',
    GMD: 'https://example.com/flags/gmd.png',
    GNF: 'https://example.com/flags/gnf.png'
  };
  
  export default flags;
  